#!/usr/bin/env bash
set -e

DOTFILES_HOME="$HOME/.local/share/yadm/repo.git"

if [[ ! -d "${DOTFILES_HOME}" ]]; then
    brew install yadm

    # yadm clone https://github.com/nachovizzo/dotfiles.git
    cp -r /opt/dotfiles/.git ${DOTFILES_HOME}
    yadm checkout $HOME
fi

yadm pull
yadm bootstrap
