#!/usr/bin/env bash
set -e

DOTFILES_GIT_REPO="$HOME/.local/share/yadm/repo.git"

brew install yadm

# replicate yadm clone https://github.com/nachovizzo/dotfiles.git
mkdir -p $HOME/.local/share/yadm/
cp -r /opt/dotfiles/.git ${DOTFILES_GIT_REPO}
yadm checkout $HOME

# Pour cache into home directory
cp -r /opt/dotfiles/.cache/ $HOME

echo "dotfiles already initialized and initialized, run:\n\n\n\n
$ yadm bootstrap
"
