#!/usr/bin/env bash
set -xe
cd "$(dirname "$(realpath "$0")")"

export DOTFILES_REPO="https://github.com/nachovizzo/dotfiles.git"
export DOTFILES_DIR="_opt"
export HOMEBREW_CACHE="${DOTFILES_DIR}/.cache/Homebrew"

# First clone the dotfiles :)
git -C ${DOTFILES_DIR} pull || git clone ${DOTFILES_REPO} ${DOTFILES_DIR}

# Environment Setup
cp env.sh ${DOTFILES_DIR}/.env.sh
cp adeinit ${DOTFILES_DIR}/.adeinit
